services:
  # Web Server (PHP + Laravel development server)
  web:
    build: .
    container_name: docs_engine
    ports:
      - "8004:8000"  # Map host port 8080 to container port 8000 (default for 'php artisan serve')
    volumes:
      - .:/var/www/html  # Mount the current directory to the container
      - storage:/var/www/html/storage  # Mount the shared storage volume
    networks:
      - docs_network
    command: php artisan serve --host=0.0.0.0 --port=8000  # Run Laravel using the built-in server
    restart: unless-stopped  # Automatically restart the container unless it is explicitly stopped
    depends_on:
      - redis  # Ensures Redis is up before the web service starts

  redis:
    image: redis
    container_name: redis
    networks:
      - docs_network

volumes:
  storage:  # Declare a volume to share the 'storage' directory between containers

networks:
  docs_network:
    driver: bridge